# ==========================================
# MARS ROVER ROCKS SETS GROUND TRUTH
# ==========================================
maps:
  easy:
    - [0.85, 6.88]
    - [-11.98, 7.91]
    - [11.97, 8.31]
    - [25.95, 30.55]
    - [10.0, 18.69]

  medium:
    - [0.85, 6.88]
    - [-11.98, 7.91]
    - [11.97, 8.31]
    - [25.95, 30.55]
    - [10.0, 18.69]
    - [-6.56, 5.8]
    - [-5.0, 19.5]
    - [-6.3, -7.96]
    - [-5.0, 0.5]

  hard:
    - [0.85, 6.88]
    - [-11.98, 7.91]
    - [11.97, 8.31]
    - [25.95, 30.55]
    - [10.0, 18.69]
    - [-6.56, 5.8]
    - [-5.0, 19.5]
    - [-6.3, -7.96]
    - [-5.0, 0.5]
    - [-4.20, 6.99]
    - [8.2, 2.5]      
    - [-13, 14.5]
    - [17.0, 19.0]
    - [0.6, 17.69]
    - [-2.0, 22.69]
    - [9.0, 11.5]
    - [-12.0, 11.5]

waypoints:
  path_1:
    start: [0.0, 0.0]
    wp1: [21.7, 26.4]
    wp2: [0.5, 11.0]
  path_2:
    start: [-11.0, -12.5]
    wp1: [5.2, 6.5]
    wp2: [5.0, 16.0]
  path_3:
    start: [-13.0, 9.0]
    wp1: [-5.0, 13.0]
    wp2: [-3.0, 20.0]    