# ==========================================
# MARS ROVER NAV2 CONFIGURATION
# ==========================================

#global costmap params
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[ [2.341, 1.469], [-1.841, 1.469], [-1.841, -1.469], [2.341, -1.469] ]"
      footprint_padding: 0.15
      use_sim_time: True
      resolution: 0.1
      track_unknown_space: true
      width: 100
      height: 100
      origin_x: -50.0
      origin_y: -50.0
      plugins: ["obstacle_layer", "inflation_layer"]
      
      # Pointcloud params
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: semantic_cloud
        semantic_cloud:
          topic: /semantic_obstacles
          sensor_frame: base_link
          max_obstacle_height: 2.0
          clearing: False       # no clearing
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          obstacle_max_range: 10.0

      # Inflation layer params with 1 meter safety buffer, so objects on the map are a dot with 1 meter around them
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 3.0

# local costmap params
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link # robot base link connection to the map
      footprint: "[ [2.341, 1.469], [-1.841, 1.469], [-1.841, -1.469], [2.341, -1.469] ]"
      footprint_padding: 0.15
      use_sim_time: True
      rolling_window: true # moving map with rover
      width: 10
      height: 10
      resolution: 0.1
      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: semantic_cloud
        semantic_cloud:
          topic: /semantic_obstacles
          sensor_frame: base_link
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          obstacle_max_range: 10.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 1.5

# Behavior tree subtree for controller and planner management; resposible for only limited actions (main tree is higher in hierarchy)
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link

# Controller to follow the path; pure pursuit, freq important
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # PurePursuit Controller
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 2.0
      lookahead_dist: 0.5
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.0
      lookahead_time: 1.5
      use_rotate_to_heading: false
      rotate_to_heading_angular_vel: 0.0  # important because of the contraints of the controller and object (not to spin in the one spot)
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: false
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 1.0
      regulated_linear_scaling_min_speed: 0.15
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5 # checking goal with given tollerance
      yaw_goal_tolerance: 3.14  # the angles of the robot while in the desired position are not neccessary
      stateful: True

# Planner (server)
planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

# Collision monitor for planner to determine the collision with objects
collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 0.0
    stop_pub_timeout: 2.0
    
    # Rover has its own safety area 1 meter around its stopPolygon
    polygons: ["PolygonWarning", "PolygonStop"]
    
    PolygonWarning:
      type: "polygon"
      points: "[ [1.711, 1.319], [-1.711, 1.319], [-1.711, -1.319], [1.711, -1.319] ]"
      action_type: "slowdown"
      min_points: 4
      slowdown_ratio: 0.6
      visualize: True
      polygon_pub_topic: "polygon_warning"
    
    PolygonStop:
      type: "polygon"
      points: "[ [1.06, 0.79], [-1.06, 0.79], [-1.06, -0.79], [1.06, -0.79] ]"
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "polygon_stop"
      
    # Forcing the monitor to use pointcloud of the rgbd and lidar data
    observation_sources: ["semantic_cloud"]
    semantic_cloud:
      type: "pointcloud"
      topic: "/semantic_obstacles"

# Docking server (only for the purpose of ROS2 itself, the robot doesnt have charging/docking station)
docking_server:
  ros__parameters:
    use_sim_time: True
    base_frame: "base_link"
    odom_frame: "odom"
    dock_plugins: ['dummy_dock']
    dummy_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      staging_x_offset: -0.5
      use_external_detection_pose: false
      use_battery_status: false

# velocity and acceleration contraints managing
velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 10.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [2.0, 0.0, 1.0]   # [x, y, theta] rover cant move sideways so v_y=0
    min_velocity: [-2.0, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]      